version: '3'

services:
    app:
        build: .
        image: super-markit:latest
        ports:
            - "8000:80"
        env_file:
            - .env
        volumes:
            - ./:/var/www/html
        depends_on:
            - mariadb
            - redis-commander
            - minio

    mariadb:
        image: mariadb:10.6.15
        environment:
            MARIADB_DATABASE: ${MARIADB_DATABASE}
            MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        depends_on:
            - mariadb
        environment:
            PMA_HOST: mariadb
            PMA_PORT: 3306
            PMA_ARBITRARY: 1
        restart: on-failure
        ports:
            - "8080:80"

    minio:
        image: bitnami/minio:2024.1.18
        ports:
            - "9000:9000"
            - "9001:9001"
        environment:
            MINIO_ROOT_USER: ${ACCESS_ID}
            MINIO_ROOT_PASSWORD: ${SECRET_KEY}
            MINIO_DEFAULT_BUCKETS: ${BUCKET_NAME}

    redis:
        container_name: redis
        hostname: ${REDIS_HOST}
        image: redis:7.0-alpine

    redis-commander:
        container_name: redis-commander
        hostname: redis-commander
        image: rediscommander/redis-commander:latest
        restart: on-failure
        environment:
            REDIS_HOSTS: ${REDIS_HOSTS}
        ports:
            - "8081:8081"
        depends_on:
            - redis

    test:
        build: .
        command: "wait-for-it 'mariadb:3306' -- php bin/phpunit --coverage-html coverage"
        image: super-markit/test:latest
        depends_on:
            - mariadb
            - redis
            - minio
        env_file:
            - .env
        volumes:
            - ./:/var/www/html
